In [1]:
import torch
import numpy as np

In [11]:
m = 2
num_feature = 5
BT_P = torch.Tensor(np.arange(1,50+1).transpose().reshape([-1,5]) ,).type(torch.DoubleTensor)

In [12]:
BT_P = BT_P.t()

In [13]:
BT_P

tensor([[ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.],
        [ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47.],
        [ 3.,  8., 13., 18., 23., 28., 33., 38., 43., 48.],
        [ 4.,  9., 14., 19., 24., 29., 34., 39., 44., 49.],
        [ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.]],
       dtype=torch.float64)

In [14]:
U, Sigma, _  = BT_P.t().matmul(BT_P).svd()

In [15]:
_thres = 1e-12
Sigma[Sigma.data <= _thres] = 0.0
Sigma

tensor([4.2901e+04, 2.4038e+01, 2.6825e-12, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00], dtype=torch.float64)

In [16]:
nnz = Sigma.nonzero().numel()
V = BT_P.matmul(U[:, :nnz]).matmul(  (1/Sigma[:nnz].sqrt()).diag()   )

In [17]:
BT_P = V[:, :m - 1].matmul((Sigma[:m - 1] - Sigma[m]).sqrt().diag())
BT_P


#BT_P = torch.cat([self.BT_P, torch.zeros([self.num_feature, self.m + 1]).double() ], 1)

tensor([[-87.0335],
        [-89.7903],
        [-92.5472],
        [-95.3041],
        [-98.0610]], dtype=torch.float64)

In [18]:
BT_P = torch.cat([BT_P, torch.zeros([num_feature, m + 1]).double() ], 1)
BT_P

tensor([[-87.0335,   0.0000,   0.0000,   0.0000],
        [-89.7903,   0.0000,   0.0000,   0.0000],
        [-92.5472,   0.0000,   0.0000,   0.0000],
        [-95.3041,   0.0000,   0.0000,   0.0000],
        [-98.0610,   0.0000,   0.0000,   0.0000]], dtype=torch.float64)

In [19]:
BT_P = V[:, :nnz].matmul((Sigma[:nnz]).sqrt().diag())
BT_P

tensor([[-8.7033e+01,  3.1904e+00, -3.3307e-14],
        [-8.9790e+01,  1.6413e+00, -7.7716e-15],
        [-9.2547e+01,  9.2289e-02,  1.6875e-14],
        [-9.5304e+01, -1.4568e+00,  4.1467e-14],
        [-9.8061e+01, -3.0058e+00,  6.5170e-14]], dtype=torch.float64)

In [20]:
 torch.cat([BT_P, torch.zeros([num_feature, (2 * m) - nnz]).double() ], 1)

tensor([[-8.7033e+01,  3.1904e+00, -3.3307e-14,  0.0000e+00],
        [-8.9790e+01,  1.6413e+00, -7.7716e-15,  0.0000e+00],
        [-9.2547e+01,  9.2289e-02,  1.6875e-14,  0.0000e+00],
        [-9.5304e+01, -1.4568e+00,  4.1467e-14,  0.0000e+00],
        [-9.8061e+01, -3.0058e+00,  6.5170e-14,  0.0000e+00]],
       dtype=torch.float64)

In [ ]:
self.BT_P[:,self.row_count_p] = np.sqrt(-self.eta*sign)*alpha.squeeze()


if self.row_count_p == 2*self.m - 1  :

    U, Sigma, _ = (self.BT_P.t().matmul(self.BT_P)).svd()
    Sigma[Sigma.data <= self._thres] = 0.0
    nnz = Sigma.nonzero().numel()
    V = self.BT_P.matmul(U[:, :nnz]).matmul(  (1/Sigma[:nnz].sqrt()).diag()   )


    if nnz >= self.m:

        self.BT_P = V[:, :self.m - 1].matmul((Sigma[:self.m - 1] - Sigma[self.m]).sqrt().diag())
        self.BT_P = torch.cat([self.BT_P, torch.zeros([self.num_feature, self.m + 1]).double() ], 1)
        self.row_count_p = self.m - 1

    else:
        self.BT_P = V[:, :nnz].matmul((Sigma[:nnz]).sqrt().diag())
        self.BT_P= torch.cat([self.BT_P, torch.zeros([self.num_feature, (2 * self.m) - nnz]).double() ], 1)
        self.row_count_p = nnz